name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy artifact
      uses: github/maven-publish@v2
      with:
        maven-version: '3.8.3'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pom: 'pom.xml'
        file: 'target/*.jar' # Adjust the file pattern to match your artifact
