name: Java Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Change this to match your Java version
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-java-package
        path: target/*.jar
