name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy artifact
      uses: MavenPublish/action@v2
      with:
        maven-version: '3.8.3'
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        file-to-publish: target/*.jar # Adjust the file pattern to match your artifact
